#!/usr/bin/env bash

#encrypt text in clipboard to self and recipients, and send back to clipboard
rp=""
for var in "$@"
do
    rp+=" -r $var"
done

self=0x6EC2B0C2
pbpaste | eval "gpg -a -u $self -r $self $rp -s -e" | pbcopy

